### ISSUE TITLE
AdguardHome_Upstreams_Autoupdate.txt  文件格式有问题，需要调整下。

### ISSUE THREAD

**Issue by thomas-888** [rwx9032/AdguardHome#3]
AdGuardHome 信息：
<img width="702" alt="image" src="https://user-images.githubusercontent.com/53040255/176996755-a6b4a8b1-f667-459c-98ad-a0860eea8b8b.png">
操作系统信息：
CPU架构: X86-64
OS: Debian10

错误的写法：
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/53040255/176996533-851086d2-e1a8-43e1-8c17-f0a0358360f1.png">
[//000webhost.com]tls://1.1.1.1
[//030buy.com]tls://1.1.1.1
[//0rz.tw]tls://1.1.1.1
[//1-apple.com.tw]
tls://1.1.1.1
[//10.tt]tls://1.1.1.1

正确的写法：

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/53040255/176996659-38e40ef3-9425-48b4-a617-540f683110e3.png">
[/000webhost.com/]tls://1.1.1.1
[/030buy.com/]tls://1.1.1.1
[/0rz.tw/]tls://1.1.1.1
[/1-apple.com.tw/]tls://1.1.1.1
[/10.tt/]tls://1.1.1.1

**Comment by thomas-888** [comment]
调整命令：
sed -i 's/\[\/\//\[\//g' ./AdguardHome_Upstreams_Autoupdate.txt 
sed -i 's/\]/\/\]/g' ./AdguardHome_Upstreams_Autoupdate.txt

**Comment by rwx9032** [comment]
感谢反馈 正在修复:)
